### ISSUE TITLE
How do I get SR working? I installed using pip3.

### ISSUE THREAD

**Issue by LinuxBeaver** [fengwang/super_resolution#1]
(base) [contrast@#### Desktop]$ super_resolution /home/contrast/Desktop/bottle.png bottle2.png_4X
WARNING:tensorflow:From /home/contrast/Applications/mc/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Failed to find weights from file /home/contrast/Applications/mc/lib/python3.8/site-packages/super_resolution/resources/cartoon_model/weights.h5
Traceback (most recent call last):
  File "/home/contrast/Applications/mc/bin/super_resolution", line 8, in <module>
    sys.exit(main())
  File "/home/contrast/Applications/mc/lib/python3.8/site-packages/super_resolution/entry_points.py", line 24, in main
    cartoon_upsampling_4x( input_image_path, output_image_path )
  File "/home/contrast/Applications/mc/lib/python3.8/site-packages/super_resolution/super_resolution.py", line 208, in cartoon_upsampling_4x
    ans = cartoon_model.predict( im, batch_size=1 )
AttributeError: 'NoneType' object has no attribute 'predict'
(base) [contrast@#### Desktop]$

**Comment by supervoids** [comment]
I got the same error message:

AttributeError: 'NoneType' object has no attribute 'predict'
Failed to find weights from file /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/super_resolution/resources/cartoon_model/weights.h5

Looks like the directory **resources** and the subdirectories with the model files (**weights.h5** and **js.json** for both 4x and 8x upsampling) are missing when installing via pip.

You can download the resources directory from [here](https://github.com/fengwang/super_resolution/tree/master/super_resolution) and move it to: .../site-packages/super_resolution/ 

The script super_resolution.py should then be able to load the model(s) successfully. Some TensorFlow deprecation warnings might occur, but otherwise it should work. Just tested and I got it to work this way.

**Comment by LinuxBeaver** [comment]
Thank you. I got it working. I wish I could give the app training data by adding images of caps, and bottles.

I do not know how to edit h5 files so I have no chance of training this myself.

**Comment by MarcelWaldvogel** [comment]
I am trying to prepare a [PR](https://github.com/MarcelWaldvogel/super_resolution/tree/include-training-data) to fix this. Installing this results the files being in `…/super_resolution/resources/cartoon_model*/*`. Running results in #2. Running it with `python3 -c "from super_resolution.entry_points import main; main()"` results in the "non-resource variables are not supported in the long term" warning and nothing happens. What are you doing differently?

**Comment by fengwang** [comment]
@MarcelWaldvogel Many thanks for the PR. I have merged it.
@LinuxBeaver I have updated the pip package, can you please try again?

**Comment by nsankar** [comment]
@LinuxBeaver  This problem still exists when i installed and tried it from the latest pip install 

![image](https://user-images.githubusercontent.com/431890/147331220-25bb2da0-ea07-4d47-94da-0b2d85d064d5.png)

**Comment by fengwang** [comment]
@nsankar I have uploaded the pre-trained models to github, and load them for the first time. Should work with the most recent version (0.2.4).
